#!/usr/bin/python
# -*- coding: UTF-8 -*-

import MySQLdb

# 打开数据库连接
db = MySQLdb.connect(host = "172.16.111.87",port = 3306,user = "root",passwd = "",db = "Spider" ,charset='utf8')

# 使用cursor()方法获取操作游标 
cursor = db.cursor()

# 如果数据表已经存在使用 execute()
cursor.execute("select * from GrabSite")
results = cursor.fetchall()

print results

# 关闭数据库连接
db.close()